### ISSUE TITLE
请问抓取课表的语句具体怎么写呢

### ISSUE THREAD

**Issue by juquxiang** [QingQiz/AoxiangRobot#18]
我按照aoxiangRobot -u 2017000000 -p ./password classTable -o res.ics -a 20语句运行会报以下错误
![image](https://user-images.githubusercontent.com/73006913/126037339-0a933136-15a2-4a08-bcee-935fc4167447.png)

另外请问我能进行二次开发做app吗

**Comment by QingQiz** [comment]
嗯，翱翔门户课表接口变了，我处理一下

至于二次开发，请遵守 `LGPL-3.0 License`

**Comment by QingQiz** [comment]
修好了，参见 https://github.com/QingQiz/python_modules/commit/61f77b0a4b597d48ab5882dd1ab40bc389f621ac https://github.com/QingQiz/python_modules/commit/743aec4617024e8110de00141d25a2f59ca0aee0 150071e235d54c02c9dd054c036e4e70f1ed5851

执行 `git pull` 和 `pip install --upgrade -r requirements.txt` 获取更新
