### ISSUE TITLE
20211222改版后似乎挂了？

### ISSUE THREAD

**Issue by moetayuko** [QingQiz/AoxiangRobot#20]
这个正则好像挂了
https://github.com/QingQiz/AoxiangRobot/blob/7bab4f353bcf4bdef9e125d2ea9f546f230db386/src/netreq/aoxiang.py#L599

**Comment by QingQiz** [comment]
```
# cat x.py
import re


html = open('x.html').read()

print(re.findall(r'i class=.co4.>(.*?)</i', html))


# python3 x.py
['您已提交今日填报，重新提交将覆盖上一次的信息。']
```

测试了，没挂啊

**Comment by moetayuko** [comment]
今天又试了一下，似乎每天第一次填报前是挂的，手动填报后才会正常。。
这是今天刚抓的填报前输入正则的html http://fars.ee/B5gz 里边没有col4
个人信息应该全部隐去了，如果发现有漏的麻烦提醒一下（

**Comment by QingQiz** [comment]
我知道原因了。这个正则是用来检测疫情填报是否成功的。最近西安疫情，应该是请求参数变了，导致疫情填报失败，所以挂了。。。

```json
{"state":"-2","err_msg":"系统已记录您的非正常操作，所有绕过系统页面正常操作以外的的行为，都将视为网络攻击行为！"}
```

这是现在的请求结果。。。

**Comment by QingQiz** [comment]
![AUWAG`T`DUB7F%TI{9177HC](https://user-images.githubusercontent.com/33107216/147390700-0c919e28-f810-4e18-9180-7d8ee62640bf.png)

学校这个有点意思2333333

---

总之修好了 3e1de6fab2e6033149c453814ad296fdbdae9e97
